### ISSUE TITLE
SelectAll/DeselectAll

### ISSUE THREAD

**Issue by PierGiorgioMingoia** [kfrancikowski/react-multiselect-dropdown-bootstrap#1]
Hi, now after the new release the SelectAll/DeselectAll button return a list of [Obj object] instead of the original value.

**Comment by kfrancikowski** [comment]
Ah, yes, i though that i've uploaded a fix two days ago :) Now it should work fine. I've uploaded a new version to npmjs (1.0.7 and all above). Please try now.
