### ISSUE TITLE
"Select/Deselect All" refreshing page

### ISSUE THREAD

**Issue by ygorpinto** [kfrancikowski/react-multiselect-dropdown-bootstrap#17]
when I click the button (Select/Deselect All) , the page reloads automatically...
Is this the correct behaviour?

**Comment by jaypozo** [comment]
I am also experiencing this issue.

**Comment by ygorpinto** [comment]
> I am also experiencing this issue.

I solved
it was a form that was involving the button, check in your project, it could be the same thing
