### ISSUE TITLE
two way data binding is not working between selected and the state

### ISSUE THREAD

**Issue by seetharaghavan** [kfrancikowski/react-multiselect-dropdown-bootstrap#2]
Hi, 
I like this plugin , it is simple and straight forward. But when i try two way binding it is not working. Eg: Pre populating selected with state values is not getting updated eg: selected = {this.state.selected} is not working on setState

**Comment by stefanDeveloper** [comment]
I'd take this issue over and create an PR. Could you provide me an example?

**Comment by lauracabre** [comment]
Was this issue resolved? I am having the same problem. Basically it won't refresh when the state changes. Is there a way to refresh the dropdown somehow?
