### ISSUE TITLE
Error when selected array has only one element

### ISSUE THREAD

**Issue by youngestdj** [kfrancikowski/react-multiselect-dropdown-bootstrap#8]
If you pass an array of only one element to the selected prop it throws an array. It requires two or more elements to work.

```
<DropdownMultiSelect
                        options={[{key: '1', label: 'one'}, {key: '2', label: 'two'}]}
                        selected={['1']}
                        handleOnChange={(selected) =>
                         console.log(selected)
                        }

                      />
```

passing `['1','2']` to selected works

**Comment by kfrancikowski** [comment]
Hey, I've just uploaded some fixes. Can you try it now?

**Comment by youngestdj** [comment]
Still doesn't work. Throw "Type error: o is undefined"

**Comment by kfrancikowski** [comment]
You can try to use 1.1.0 version. I've tried to reproduce this error with 1.1.0 and everything is working fine. I've created a test case like this:
`import DropdownMultiselect from 'react-multiselect-dropdown-bootstrap';

const options = [
  { id: 1, name: "Potatoes" },
];

const optionsSimple = ["Potatoes"];

function App() {
  return (
    <div className="App">
      <div className="row">
        <div className="col-md-4">
          <DropdownMultiselect options={optionsSimple} name="dropdown1" handleOnChange={(selected) => {console.log(selected)}} />
        </div>
        <div className="col-md-4">
          <DropdownMultiselect optionLabel="name" optionKey="id" options={options} name="dropdown2" handleOnChange={(selected) => {console.log(selected)}} />
        </div>
      </div>
    </div>
  );
}

export default App;`
and it's working just fine.

**Comment by kfrancikowski** [comment]
I've just try to test it with this example and it's working just fine. Please try to use 1.1.0. I've made some fixes there.
```
import DropdownMultiselect from 'react-multiselect-dropdown-bootstrap';

function App() {
  return (
    <DropdownMultiselect
      options={[{key: '1', label: 'one'}, {key: '2', label: 'two'}]}
      selected={['1']}
      handleOnChange={(selected) =>
        console.log(selected)
      }

    />
  );
}

export default App;
```
