### ISSUE TITLE
On change checkbox value is not selected 

### ISSUE THREAD

**Issue by Inam337** [kfrancikowski/react-multiselect-dropdown-bootstrap#9]
Please see the attachment and find the solution of this
https://user-images.githubusercontent.com/18351912/100362728-99f3ab00-301d-11eb-84a4-ac5f1f163b34.PNG

**Comment by kfrancikowski** [comment]
You can try to use a newer version 1.1.0 but honestly i can't reproduce your error. It might be something with custom styling.
